/* 
*Copyright (c) 2019-2021, Alibaba Group Holding Limited;
*Licensed under the Apache License, Version 2.0 (the "License");
*you may not use this file except in compliance with the License.
*You may obtain a copy of the License at

*   http://www.apache.org/licenses/LICENSE-2.0

*Unless required by applicable law or agreed to in writing, software
*distributed under the License is distributed on an "AS IS" BASIS,
*WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*See the License for the specific language governing permissions and
*limitations under the License.
 */


// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agents/heartbeat": {
            "post": {
                "description": "用于 心跳报告",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent 管理"
                ],
                "summary": "心跳报告",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-luns": {
            "get": {
                "description": "用于查询所有 Cluster LUN",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LUN 管理"
                ],
                "summary": "列表 Cluster LUN",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/view.ClusterLunResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            },
            "post": {
                "description": "用于创建 Cluster LUN",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LUN 管理"
                ],
                "summary": "创建 Cluster LUN",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "clusterLun",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.ClusterLunCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-luns/:wwid": {
            "get": {
                "description": "用于查询指定 Cluster LUN",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LUN 管理"
                ],
                "summary": "查询 Cluster LUN",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LUN WWID",
                        "name": "wwid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.ClusterLunResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            },
            "delete": {
                "description": "用于删除指定 Cluster LUN",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LUN 管理"
                ],
                "summary": "删除 Cluster LUN",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LUN WWID",
                        "name": "wwid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-luns/expand": {
            "post": {
                "description": "用于扩容指定 Cluster LUN",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LUN 管理"
                ],
                "summary": "扩容 Cluster LUN",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "clusterLun",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.ClusterLunCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-luns/format": {
            "post": {
                "description": "用于格式化指定 Cluster LUN",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LUN 管理"
                ],
                "summary": "格式化 Cluster LUN",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "clusterLun",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.ClusterLunFormatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-luns/fs-expand": {
            "post": {
                "description": "用于扩容指定 Cluster LUN Filesystem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LUN 管理"
                ],
                "summary": "扩容 Cluster LUN For Filesystem",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "clusterLun",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.ClusterLunFsExpandRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-lvs": {
            "get": {
                "description": "用于列表 Cluster LV",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LV 管理"
                ],
                "summary": "列表 Cluster LV",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/view.ClusterLvResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            },
            "post": {
                "description": "用于创建 Cluster LV",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LV 管理"
                ],
                "summary": "创建 Cluster LV",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "clusterLv",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.ClusterLvCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-lvs/:name": {
            "get": {
                "description": "用于查询 Cluster LV",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LV 管理"
                ],
                "summary": "查询 Cluster LV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LV name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.ClusterLvResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            },
            "delete": {
                "description": "用于删除指定 Cluster LV",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LV 管理"
                ],
                "summary": "删除 Cluster LV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "lv name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-lvs/dm-conf": {
            "post": {
                "description": "用于生成预览的lv的配置文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LV 管理"
                ],
                "summary": "生成预览的lv的配置文件",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "clusterLv",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.GenerateDmCreateCmdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.DmCreateCmdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-lvs/expand": {
            "post": {
                "description": "用于扩容指定 Cluster LV",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LV 管理"
                ],
                "summary": "扩容 Cluster LV",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "clusterLv",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.ClusterLvCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-lvs/format": {
            "post": {
                "description": "用于格式化指定 Cluster LV",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LV 管理"
                ],
                "summary": "格式化 Cluster LV",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "clusterLv",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.ClusterLvFormatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/cluster-lvs/fs-expand": {
            "post": {
                "description": "用于扩容指定 Cluster LV Filesystem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LV 管理"
                ],
                "summary": "扩容 Cluster LV For Filesystem",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "clusterLv",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.ClusterLvFsExpandRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/events": {
            "post": {
                "description": "用于存储事件上报",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event 接入管理"
                ],
                "summary": "Event Upload",
                "parameters": [
                    {
                        "type": "string",
                        "name": "body",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "eType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/events/batch": {
            "post": {
                "description": "用于存储事件上报",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event 接入管理"
                ],
                "summary": "Batch Event Upload",
                "parameters": [
                    {
                        "type": "string",
                        "name": "node_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pr-check/detail": {
            "get": {
                "description": "用于检查PR所支持的能力的结果查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PR Check 接入管理"
                ],
                "summary": "Pr Check Detail Capability Response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求参数",
                        "name": "volumeId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求参数",
                        "name": "volumeClass",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.PrCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            },
            "post": {
                "description": "用于检查PR所支持的能力",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PR Check 接入管理"
                ],
                "summary": "Pr Check Detail Capability",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "pvc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.PrCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pr-check/overall": {
            "post": {
                "description": "用于获取PR所支持的能力",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PR Check 接入管理"
                ],
                "summary": "Pr Check Overall Capability",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "pvc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.PrCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.PrCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pvcs": {
            "get": {
                "description": "用于查询指定pvc列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "查询pvc 列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pvc used volumeType",
                        "name": "volumeType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/view.PvcResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            },
            "post": {
                "description": "用于创建 PVC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "创建 PVC",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "pvc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.PvcCreateWithVolumeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pvcs/:name": {
            "get": {
                "description": "用于查询指定的pvc",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "查询pvc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pvc name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pvc namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.PvcResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            },
            "delete": {
                "description": "用于删除 PVC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "删除 PVC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pvc name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pvc namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pvcs/expand": {
            "get": {
                "description": "PVC对应的数据库集群扩容是否结束",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "PVC扩容查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "workflowId",
                        "name": "workflowId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.PvcExpandFsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            },
            "post": {
                "description": "PVC对应的数据库集群扩容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "PVC扩容",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "pvc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.PvcExpandFsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pvcs/format": {
            "post": {
                "description": "用于PVC format",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "PVC format",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "pvc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.PvcFormatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pvcs/formatAndLock": {
            "post": {
                "description": "用于PVC 强制format和lock, 添加写锁节点, 集群中只有一个节点可以添加写锁",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "PVC 强制format和lock",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "pvc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.PvcWriteLockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pvcs/lock": {
            "post": {
                "description": "用于PVC 添加写锁节点, 集群中只有一个节点可以添加写锁",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "PVC 添加写锁节点",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "pvc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.PvcWriteLockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pvcs/ready": {
            "get": {
                "description": "用于创建集群时，查询PVC是否准备完，可以使用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "查询 PVC是否ready",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pvc name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "workflowId",
                        "name": "workflowId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.PvcIsReadyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pvcs/release": {
            "post": {
                "description": "用于释放 PVC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "释放 PVC",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "pvc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.PvcRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pvcs/topo": {
            "get": {
                "description": "用于集群校验读写拓扑，查询磁盘在集群各个节点的读写权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "查询 PVC后端的磁盘读写权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pvc name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "workflowId",
                        "name": "workflowId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pvc namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.PvcVolumePermissionTopoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/pvcs/use": {
            "post": {
                "description": "创建集群的时候，指定使用 PVC, 默认需要Bind Pvc和已有的磁盘，更新pvc和volume的状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVC 接入管理"
                ],
                "summary": "使用 PVC",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "pvc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.PvcBindVolumeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/scsi/rescan": {
            "post": {
                "description": "用于扫描 Volume Rescan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scsi 管理"
                ],
                "summary": "扫描 Volume Rescan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        },
        "/workflows/:workflowId": {
            "get": {
                "description": "用于查询 WorkflowEntity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow 管理"
                ],
                "summary": "查询 WorkflowEntity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求参数",
                        "name": "workflowId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/view.WorkflowResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/view.ErrorResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.VolumeStatus": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "status_value": {
                    "type": "integer"
                }
            }
        },
        "lv.PrCheckList": {
            "type": "object",
            "properties": {
                "support_pr_7": {
                    "type": "boolean"
                },
                "support_pr_attempt": {
                    "type": "boolean"
                },
                "support_pr_clear": {
                    "type": "boolean"
                },
                "support_pr_register": {
                    "type": "boolean"
                },
                "support_pr_release": {
                    "type": "boolean"
                },
                "support_pr_reserve": {
                    "type": "boolean"
                }
            }
        },
        "lv.PrInfo": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/lv.PrCheckList"
            }
        },
        "protocol.Event": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "eType": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "view.ClusterLunCreateRequest": {
            "type": "object",
            "properties": {
                "cluster_id": {
                    "type": "integer"
                },
                "desc": {
                    "type": "string"
                },
                "fs_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "node_ids": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "pr_support_status": {
                    "type": "string"
                },
                "sector_num": {
                    "type": "integer"
                },
                "sector_size": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "vendor": {
                    "type": "string"
                },
                "wwid": {
                    "type": "string"
                }
            }
        },
        "view.ClusterLunFormatRequest": {
            "type": "object",
            "properties": {
                "fs_size": {
                    "type": "integer"
                },
                "fs_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "wwid": {
                    "type": "string"
                }
            }
        },
        "view.ClusterLunFsExpandRequest": {
            "type": "object",
            "properties": {
                "fs_size": {
                    "type": "integer"
                },
                "fs_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pv_name": {
                    "type": "string"
                },
                "wwid": {
                    "type": "string"
                }
            }
        },
        "view.ClusterLunResponse": {
            "type": "object",
            "properties": {
                "cluster_id": {
                    "type": "integer"
                },
                "db_cluster_name": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "fs_size": {
                    "type": "integer"
                },
                "fs_type": {
                    "type": "string"
                },
                "lv_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "node_ids": {
                    "type": "string"
                },
                "path_num": {
                    "type": "integer"
                },
                "paths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pr_support_status": {
                    "type": "string"
                },
                "product": {
                    "type": "string"
                },
                "pvc_name": {
                    "type": "string"
                },
                "sector_num": {
                    "type": "integer"
                },
                "sector_size": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/domain.VolumeStatus"
                },
                "usable": {
                    "type": "boolean"
                },
                "used_size": {
                    "type": "integer"
                },
                "vendor": {
                    "type": "string"
                },
                "volume_type": {
                    "type": "string"
                },
                "wwid": {
                    "type": "string"
                }
            }
        },
        "view.ClusterLvCreateRequest": {
            "type": "object",
            "properties": {
                "dm_table": {
                    "type": "string"
                },
                "fs_type": {
                    "type": "string"
                },
                "luns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.MultipathVolumeView"
                    }
                },
                "mode": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "node_ids": {
                    "type": "string"
                },
                "sector_num": {
                    "type": "integer"
                },
                "sector_size": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "view.ClusterLvFormatRequest": {
            "type": "object",
            "properties": {
                "fs_size": {
                    "type": "integer"
                },
                "fs_type": {
                    "type": "string"
                },
                "volume_id": {
                    "type": "string"
                },
                "volume_name": {
                    "type": "string"
                }
            }
        },
        "view.ClusterLvFsExpandRequest": {
            "type": "object",
            "properties": {
                "fs_type": {
                    "type": "string"
                },
                "req_size": {
                    "type": "integer"
                },
                "volume_id": {
                    "type": "string"
                },
                "volume_name": {
                    "type": "string"
                }
            }
        },
        "view.ClusterLvResponse": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.MultipathVolumeView"
                    }
                },
                "cluster_id": {
                    "type": "integer"
                },
                "db_cluster_name": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "fs_size": {
                    "type": "integer"
                },
                "fs_type": {
                    "type": "string"
                },
                "lv_name": {
                    "type": "string"
                },
                "node_ids": {
                    "type": "string"
                },
                "pr_support_status": {
                    "type": "string"
                },
                "pvc_name": {
                    "type": "string"
                },
                "sector_num": {
                    "type": "integer"
                },
                "sector_size": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/domain.VolumeStatus"
                },
                "usable": {
                    "type": "boolean"
                },
                "used_size": {
                    "type": "integer"
                },
                "volume_id": {
                    "type": "string"
                },
                "volume_name": {
                    "type": "string"
                },
                "volume_type": {
                    "type": "string"
                }
            }
        },
        "view.DmCreateCmdResponse": {
            "type": "object",
            "properties": {
                "lv_name": {
                    "type": "string"
                },
                "lv_type": {
                    "type": "string"
                },
                "preview_conf": {
                    "type": "string"
                },
                "sector_size": {
                    "type": "integer"
                },
                "sectors": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "view.ErrorResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "view.GenerateDmCreateCmdRequest": {
            "type": "object",
            "properties": {
                "lun_ids_in_order": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lv_name": {
                    "type": "string"
                },
                "lv_type": {
                    "type": "string"
                }
            }
        },
        "view.MultipathVolumeView": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sector_num": {
                    "type": "integer"
                },
                "sector_size": {
                    "type": "integer"
                },
                "volume_id": {
                    "type": "string"
                }
            }
        },
        "view.Node": {
            "type": "object",
            "properties": {
                "node_id": {
                    "type": "string"
                },
                "node_ip": {
                    "type": "string"
                }
            }
        },
        "view.PrCheckRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "volume_id": {
                    "type": "string"
                },
                "volume_type": {
                    "type": "string"
                }
            }
        },
        "view.PrCheckResponse": {
            "type": "object",
            "properties": {
                "pr_info": {
                    "$ref": "#/definitions/lv.PrInfo"
                }
            }
        },
        "view.PvcBindVolumeRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "need_format": {
                    "type": "boolean"
                },
                "resource_id": {
                    "description": "pvc对应的clusterID",
                    "type": "string"
                },
                "storage_class": {
                    "type": "string"
                },
                "volume_id": {
                    "type": "string"
                },
                "volume_type": {
                    "type": "string"
                }
            }
        },
        "view.PvcCreateWithVolumeRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "need_format": {
                    "type": "boolean"
                },
                "volume_id": {
                    "type": "string"
                },
                "volume_type": {
                    "type": "string"
                }
            }
        },
        "view.PvcExpandFsRequest": {
            "type": "object",
            "properties": {
                "fs_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "req_size": {
                    "type": "integer"
                },
                "volume_id": {
                    "type": "string"
                },
                "volume_type": {
                    "type": "string"
                }
            }
        },
        "view.PvcExpandFsResponse": {
            "type": "object",
            "properties": {
                "err_message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "view.PvcFormatRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "view.PvcIsReadyResponse": {
            "type": "object",
            "properties": {
                "is_ready": {
                    "type": "boolean"
                }
            }
        },
        "view.PvcRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "view.PvcResponse": {
            "type": "object",
            "properties": {
                "db_cluster_name": {
                    "type": "string"
                },
                "fs_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "size_in_byte": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/domain.VolumeStatus"
                },
                "usable": {
                    "type": "boolean"
                },
                "volume_id": {
                    "type": "string"
                },
                "volume_name": {
                    "type": "string"
                },
                "volume_type": {
                    "type": "string"
                }
            }
        },
        "view.PvcVolumePermissionTopoResponse": {
            "type": "object",
            "properties": {
                "read_nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Node"
                    }
                },
                "write_node": {
                    "$ref": "#/definitions/view.Node"
                }
            }
        },
        "view.PvcWriteLockRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "write_lock_node_id": {
                    "type": "string"
                },
                "write_lock_node_ip": {
                    "type": "string"
                }
            }
        },
        "view.WorkflowIdResponse": {
            "type": "object",
            "properties": {
                "workflow_id": {
                    "type": "string"
                }
            }
        },
        "view.WorkflowResponse": {
            "type": "object",
            "properties": {
                "mode": {
                    "type": "integer"
                },
                "stages": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "step": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                },
                "workflow_id": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "127.0.0.1:2002",
	BasePath:    "/v2",
	Schemes:     []string{},
	Title:       "PolarDB Storage Manage System",
	Description: "v1.8 存储管理系统",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
